#+latex_compiler: xelatex
#+latex_class: article
#+options: toc:nil num:nil
#+title: Interpretability logics
#+author: Jan Mas Rovira
#+subtitle: Master's thesis

#+latex_header: \usepackage{unicode-math}
#+latex_header: \usepackage{fontspec}
#+latex_header: \usepackage[x11names, table]{xcolor}
#+latex_header: \usepackage[margin=2.5cm]{geometry}
#+latex_header: \usepackage{lmodern}
#+latex_header: \setmonofont{FreeMono}
#+latex_header: \usepackage{cancel}

#+latex_header: \hypersetup{colorlinks=true,urlcolor=DodgerBlue4,linkcolor=Firebrick4,citecolor=Green4}
#+latex_header: \newcommand{\ie}[0]{i.e.\ }
#+latex_header: \newcommand{\todo}[0]{\textcolor{red}{pending}}
#+latex_header: \newcommand{\pend}[0]{\textcolor{Tomato3}{pending }}
#+latex_header: \newcommand{\ok}[0]{\textcolor{DeepSkyBlue4}{solved }}
#+macro: color @@latex:{\color{$1}@@$2@@latex:}@@
#+macro: red @@latex:{\color{red}@@$1@@latex:}@@

* Frame condition for $ILR_1$
  Some definitions:
  1. $R^{-1}[E] â‰” \{x : âˆƒyâˆˆE. xRy\}$. $E$ denotes a set.
  2. $Râ‚“^{-1}[E]â‰”R^{-1}[E]âˆ©R[x]$. $E$ denotes a set.

  The $R_1$ principle reads as follows:
  \[A â–· B â†’ (Â¬(A â–· Â¬C)âˆ§ (Dâ–·â™¢E))â–·(Bâˆ§â–¡Câˆ§(Dâ–·E))\]

  The $R_1$ condition reads as follows:
  \begin{flalign*}
  &wRxRuS_wV, Kâˆˆğ’(x,u),Î“ \\
  â‡’\ & (âˆƒV'âŠ†V)(xS_wV',R[V']âŠ†K,(âˆ€vâˆˆV')(âˆ€câˆˆK)(vRcSâ‚“Râ‚“^{-1}[Î“]â‡’(âˆƒÎ“'âŠ†Î“)cS_vÎ“'))
  \end{flalign*}

  *Theorem*.
  $$ğ”‰âŠ¨Râ‚â‡”ğ”‰âŠ¨(Râ‚)_{gen}$$

  /proof/.
  {{{red(proved in Agda)}}}
  # 1. If $ğ”‰âŠ­(Râ‚)_{gen}$ then $ğ”‰âŠ¬R$ \pend.
  - \boxed{â‡’} Assume for a contradiction that $ğ”‰âŠ­(Râ‚)_{gen}$. It follows that there exist $w,x,u,V,K,Î“$ such that $wRxRuS_wV$, $Kâˆˆğ’(x,u)$ and: \[(âˆ€V'âŠ†V)(xS_wV',
    R[V']âŠ†Kâ‡’ (âˆƒvâˆˆV')(âˆƒcâˆˆK)(vRcS_xR_x^{-1}[Î“], (âˆ€Î“'âŠ†Î“) c\cancel{S}_v Î“'))\]

    Let $ğ’±$ be a family of sets defined thus:
    \[ğ’±â‰” \{U : UâŠ†V, xS_wU,R[U]âŠ†K\}\]

    From the condition it follows that for every $Uâˆˆğ’±$ the following is valid:
    \[(âˆƒv_UâˆˆU)(âˆƒc_UâˆˆK)(v_URc_US_xR_x^{-1}[Î“],(âˆ€Î“'âŠ†Î“) c_U\cancel{S}_{v_U} Î“')\]

    Let us fix such $v_U$ and $c_U$ for all $Uâˆˆğ’±$.

    Define a valuation such that the following applies:
    \begin{flalign*}
    [âŠ©a] &= \{u\} \\
    [âŠ©b] &= V \\
    [âŠ©c] &= K \\
    [âŠ©d] &= \{c_U:Uâˆˆğ’±\} \\
    [âŠ©e] &= Î“
    \end{flalign*}

    By assumption we have $w âŠ© a â–· b â†’ (Â¬(aâ–·Â¬c)âˆ§(dâ–·â™¢e))â–·(bâˆ§â–¡câˆ§(dâ–·e))$.

    It is easy to see that $w âŠ© a â–· b$ and $x âŠ© Â¬(a â–· Â¬c)$.

    Let us prove $x âŠ© dâ–·â™¢e$. Let $xRcâŠ© D$. Then $c = c_U$ for some $U âˆˆ ğ’±$. From
    the definition of $c_U$ we have $c_U S_x R_x^{âˆ’1} [Î“]$, a forcing is defined
    such that $e$ is true exactly on the set $Î“$. Hence $R_x^{-1}[Î“]âŠ©â™¢e$ and thus
    $x âŠ© dâ–·â™¢e$.

    We can also check that for $U âˆˆ ğ’±$ we have $UâŠ© b âˆ§ â–¡c$ and the following
    following condition holds for any set $U$:
    \begin{flalign*}
      (â‹†)\ xS_wU ,UâŠ© b âˆ§ â–¡câ‡’Uâˆˆ ğ’±
    \end{flalign*}
    Then since $wâŠ©aâ–·b$ and $wRxâŠ©(aâ—c)âˆ§(dâ–·â™¢e)$ there must exist some set $U$
    such that $xS_wUâŠ©bâˆ§â–¡câˆ§(dâ–·e)$. From $(â‹†)$ follows that that $Uâˆˆğ’±$ hence
    there exist $v_U,c_U$ such that $v_URc_US_xR_x^{-1}[Î“],(âˆ€Î“'âŠ†Î“)
    c_U\cancel{S}_{v_U} Î“'$. Since $c_UâŠ©d$ there must exist some $Z$ such that
    $c_US_{v_U}ZâŠ©e$, however, by the definition of the valuation it follows
    that $ZâŠ†Î“$ and thus $c_U\cancel{S}_{v_U} Z$, which is a contradiction.
  - \boxed{â‡} Suppose the $ğ”‰âŠ« (R_1)_{gen}$ and prove that $ğ”‰âŠ«R_1$. Let's fix the
    model and let $w âˆˆ W$ be arbitrary. Suppose $wâŠ© A â–·B$, and let $x$ be such
    that $wRx$ and $xâŠ© Â¬(A â–· Â¬C) âˆ§ (D â–· â™¢E)$. It follows from $x âŠ©Â¬(A â–·Â¬C)$ that
    there exists $u$ such that $xRu$, such that $uâŠ©A$, and for every $Z$ such
    that $uS_x Z$ there is some $c_Z âˆˆ Z$ such that $c_Z âŠ©C$. From $wRu$, $wâŠ©
    Aâ–· B$ and $uâŠ© A$ follows in particular that there is a $V$, $uS_w V âŠ©B$.
    Let $K â‰” \{c_Z: uS_x Z\}$. It is easy to check that $K âˆˆ ğ’(x, u)$. Let $Î“ â‰”
    [âŠ©E]$ (set of worlds that force $E$). For the selected $w, x, u, V, K, Î“$
    the property $(R 1)_{gen}$ implies that there exists $V' âŠ† V$ such that:

    \[xS_wV',R[V']âŠ†K ,(âˆ€vâˆˆV')(âˆ€câˆˆK)(vRcS_xR_x^{-1}[Î“]â‡’(âˆƒÎ“'âŠ†Î“)cS_vÎ“')\]

    We have that $V' âŠ©B$ since $V'âŠ†V$ and $V'âŠ©â–¡ C$ since $R[V']âŠ†K$. We now show
    that $V'âŠ© Dâ–· E$. Assume that for some $c âˆˆ R [V']$ we have $câŠ© D$. From
    earlier we have $xâŠ© D â–· â™¢E$. Since $c âˆˆ R [V '] âŠ† C âŠ† R [x]$, then $xRc$ so
    it follows that there exists $U$ such that $cS_x U$ and $UâŠ©â™¢E$. Clearly
    $UâŠ†[â™¢E]_x$ and also $[â™¢E]_xâŠ†R[x]$, hence by monotonicity we have
    $cS_x[â™¢E]_x$ which is the same as $cS_x R_x^{âˆ’1}[Î“]$ so by the above
    property there exists $Î“'âŠ†Î“$ such that $cS_v Î“'$. Because $Î“'âŠ†Î“$ we have
    $Î“'âŠ©E$.

# \newpage
* $RÂ¹$ Principle

  The $RÂ¹$ principle reads as follows:
  \[A â–· B â†’ (â™¢Â¬(D â–· Â¬C)âˆ§ (Dâ–·A))â–·(Bâˆ§â–¡C)\]

  The $(RÂ¹)_{gen}$ condition reads as follows:
  \begin{flalign*}
  &âˆ€w,x,y,z,ğ”¸,ğ”¹,â„‚,ğ”». \\
  &wRxRyRz, \\
  & (âˆ€u.Rwu,uâˆˆğ”¸â‡’âˆƒV.SwuV,VâŠ†ğ”¹), & \text{ensures } wâŠ©Aâ–·B \\
  & (âˆ€u.Rxu,uâˆˆğ”»â‡’âˆƒV.SxuV,VâŠ†ğ”¸), & \text{ensures } xâŠ©Dâ–·A \\
  & (âˆ€V.SyzVâ‡’âˆƒv.vâˆˆV,vâˆˆâ„‚),       &  \text{ensures } yâŠ©Â¬(Dâ–·Â¬C) \\
  & zâˆˆğ”» \\
  â‡’\ & âˆƒVâŠ†ğ”¹.xS_wV,R[V]âŠ†â„‚
  \end{flalign*}

   *Theorem*.
  $$ğ”‰âŠ¨RÂ¹â‡”ğ”‰âŠ¨(RÂ¹)_{gen}$$

  /proof/.
  {{{red(proved in Agda)}}}
  - \boxed{â‡’} Fix a frame $F$ and let $a,b,c,d$ be propositional variables and
    assume $FâŠ©a â–· b â†’ (â™¢Â¬(d â–· Â¬c)âˆ§ (dâ–·a))â–·(bâˆ§â–¡c)$. Assume that the left part of
    the implication of $(RÂ¹)_{gen}$ holds. Now let $V$ be a valuation defined by
    \begin{flalign*}
     V(u)âŠ©a &â‡” uâˆˆğ”¸ \\
     V(u)âŠ©b &â‡” uâˆˆğ”¹ \\
     V(u)âŠ©c &â‡” uâˆˆâ„‚ \\
     V(u)âŠ©d &â‡” uâˆˆğ”»
    \end{flalign*}
    Now one can easily check that $wâŠ©Aâ–·B$, $xâŠ©â™¢Â¬(Dâ–·Â¬C)âˆ§(Dâ–·A)$, hence there exists $U$
    such that $xS_wU$ and $UâŠ©Bâˆ§â–¡C$. From that we derive that $UâŠ†ğ”¹$ and $R[U]âŠ†â„‚$.
  - \boxed{â‡} Fix a model $M$ and a world $w$, we are to prove that $wâŠ©A â–· B â†’
    (â™¢Â¬(D â–· Â¬C)âˆ§ (Dâ–·A))â–·(Bâˆ§â–¡C)$. For that assume that $wâŠ©Aâ–·B$ and that for some
    $x,y,z$ we have $wRxRyRz$ and $xâŠ©Dâ–·A$, $yâŠ©Â¬(Dâ–·Â¬C)$, $zâŠ©D$. Now let
    $ğ”¸â‰”\{w:wâŠ©A\}$. We define $ğ”¹,â„‚,ğ”»$ likewise for formulas $B,C,D$ respectively.
    It is routine to check that the left part of the implication of $(RÂ¹)_{gen}$
    is met. Hence there exist a set $VâŠ†ğ”¹$ such that $xS_wV$ and $R[V]âŠ†â„‚$. By the
    definition of the sets $ğ”¹$ and $â„‚$ it follows that $VâŠ©Bâˆ§â–¡C$.

* Other principles
  Additionally, I have proved in Agda the frame condition for the following
  principles:
  - Ordinary semantics: $M$.
  - Generalized semantics: $M,R,Pâ‚€$.
