#+latex_compiler: xelatex
#+latex_class: article
#+options: toc:nil num:nil
#+title: Interpretability logics
#+author: Jan Mas Rovira
#+subtitle: Master's thesis

#+latex_header: \usepackage{unicode-math}
#+latex_header: \usepackage{fontspec}
#+latex_header: \usepackage[x11names, table]{xcolor}
#+latex_header: \usepackage[margin=2.5cm]{geometry}
#+latex_header: \usepackage{lmodern}
#+latex_header: \setmonofont{FreeMono}
#+latex_header: \usepackage{cancel}

#+latex_header: \hypersetup{colorlinks=true,urlcolor=DodgerBlue4,linkcolor=Firebrick4,citecolor=Green4}
#+latex_header: \newcommand{\ie}[0]{i.e.\ }
#+latex_header: \newcommand{\todo}[0]{\textcolor{red}{pending}}
#+latex_header: \newcommand{\red}[1]{\textcolor{red}{#1}}
#+latex_header: \newcommand{\pend}[0]{\textcolor{Tomato3}{pending }}
#+latex_header: \newcommand{\ok}[0]{\textcolor{DeepSkyBlue4}{solved }}

# * Veltman semantics in Agda
# ** Relations in Agda

#    #+begin_example
#    M , w âŠ©
#    #+end_example
# ** Veltman Frame
# * Completeness of IL
#   Assume $ILâŠ¬A$, we show that there is a model $M$ and a world $w$ such that $M,wâŠ©Â¬A$.
* Frame condition for $ILR_1$
  Some definitions:
  1. $A â— C â‰” Â¬(Aâ–·Â¬C)$.
  2. $Râ‚“^{-1}[E]â‰”R^{-1}[E]âˆ©R[x]$. $E$ denotes a set.
  3. $R^{-1}[E] â‰” \{x : âˆƒyâˆˆE. xRy\}$. $E$ denotes a set.
  4. $[A]_vâ‰”\{x : vRx âŠ© A\}$. $A$ denotes a formula.

  The R1 principle reads as follows:
  \[A â–· B â†’ (A â— C)âˆ§ (Dâ–·â™¢E)â–·Bâˆ§â–¡Câˆ§(Dâ–·E)\]

  The R1 condition reads as follows:
  \begin{flalign*}
  &wRxRuS_wV, Câˆˆğ’(x,u),EâŠ†R[v] \\
  â‡’ & (âˆƒV'âŠ†V)(xS_wV',R[V']âŠ†C,(âˆ€vâˆˆV')(âˆ€câˆˆC)(vRcSâ‚“Râ‚“^{-1}[E]â‡’cS_vE))
  \end{flalign*}

  *Lemma*
  \[ILRâ‚âŠ¢R\]


  \newpage
  *Theorem*.
  $$ğ”‰âŠ¨Râ‚â‡”ğ”‰âŠ¨(Râ‚)_{gen}$$

  /proof/.
  # 1. If $ğ”‰âŠ­(Râ‚)_{gen}$ then $ğ”‰âŠ¬R$ \pend.
  1. Now suppose the $ğ”‰âŠ« (R_1)_{gen}$ and prove that $ğ”‰âŠ«R_1$. Let's fix the
     model and let $w âˆˆ W$ be arbitrary. Suppose $wâŠ© A â–·B$, and let $x$ be such
     that $wRx$ and $xâŠ© (A â— C) âˆ§ (D â–· â™¢E)$. It follows from $x âŠ©A â—C$ that
     there exists $u$ such that $xRu$, such that $uâŠ©A$, and for every $Z$ such
     that $uS_x Z$ there is some $c_Z âˆˆ Z$ such that $c_Z âŠ©C$. From $wRu$, $wâŠ©
     Aâ–· B$ and $uâŠ© A$ follows in particular that there is a $V$, $uS_w V âŠ©B$.
     Denote $C â‰” \{c_Z: uS_x Z\}$. Obviously $C âˆˆ ğ’(x, u)$. Let $E = [E]_v$. For
     the selected $w, x, u, V, C, E$ the property $(R 1)_{gen}$ implies that
     there exists $V' âŠ† V$ such that:

     \[xS_wV',R[V']âŠ†C ,(âˆ€vâˆˆV')(âˆ€câˆˆC)(vRcS_xR_x^{-1}[E]â‡’cS_vE)\]

     It is easy to see that $V' âŠ©B âˆ§â–¡ C$. We claim that $V'âŠ© Dâ–· E$. Suppose,
     therefore, that for some $c âˆˆ R [V']$ we have $câŠ© D$. From earlier we have
     $xâŠ© D â–· â™¢E$. Since $c âˆˆ R [V '] âŠ† C âŠ† R [x]$, then $xRc$ so it follows that
     there exists $U$ such that $cS_x U$ and $UâŠ©â™¢E$. Clearly $UâŠ†[â™¢E]_x$ and also
     $[â™¢E]_x$, hence by monotonicity we have $cS_x[â™¢E]_x$. Then we have $cS_x
     R_x^{âˆ’1}[E]$ so we can use the above property and conclude that $cS_v E$.
   \newpage
  2. From $ğ”‰âŠ­(Râ‚)_{gen}$ it follows that there exist $w,x,u,V,C,E$ such that
     $wRxRuS_wV$, $Câˆˆğ’(x,u)$, $EâŠ†R^{-1}[W]$ and .

     \[(âˆ€V'âŠ†V)(xS_wV', R[V']âŠ†Câ‡’ (âˆƒvâˆˆV')(âˆƒcâˆˆC)(vRcS_xR_x^{-1}[E], c\cancel{S}_v E))\]

     As $ğ”‰âŠ¨(R)_{gen}$, there are some $UâŠ†V$ such that $xS_wU$ and $R[U]âŠ†C$. Let
     $ğ’±$ be the family of all such sets $U$. Therefore, $Uâˆˆğ’±$ and the following
     must be valid:
     \[(âˆƒv_UâˆˆU)(âˆƒc_UâˆˆC)(v_URc_US_xR_x^{-1}[E],c_U\cancel{S}_vE)\]

     Let's fix such $v_U$ and $c_U$ for all $UâŠ†V$ for which $xS_wU$ and $R[U]âŠ†C$.
     The following applies.
     \begin{flalign*}
     [A]_w &= \{u\} \\
     [B]_w &= V \\
     [C]_w &= C \\
     [D]_w &= \{c_U:Uâˆˆğ’±\} \\
     [E]_w &= E
     \end{flalign*}
    (it's always clear from context when $C$ and $E$ are prop letters and when
     sets). It's easy to see that $w âŠ© A â–· B$ and $x âŠ© A â— C$. It is
     easy to see that for $U âˆˆ ğ’±$ both $UâŠ© B âˆ§ â–¡C$ and ($â‹†$) apply: for any set
     $U$, if $xS_wU$ and $UâŠ© B âˆ§ â–¡C$, then $U âˆˆ ğ’±$ (left side of conjunction: $U
     âŠ† V â‡” U âŠ© B$; right side: $R [U] âŠ† C â‡” U âŠ©â–¡C$).

     Let us prove $x âŠ© Dâ–·â™¢E$. Let $xRcâŠ© D$. Then $c = c_U$ for some $U âˆˆ ğ’±$. From
     the definition of $c_U$ we have $c_U S_x R_x^{âˆ’1} [E]$, a forcing is defined
     such that $E$ is true exactly on the set $E$. Hence $R_x^{-1}[E]âŠ©â™¢E$ and thus
     $x âŠ© Dâ–·â™¢E$.

     Suppose $xS_w U$ and prove that $UâŠ®B âˆ§ â–¡C âˆ§ (D â–·E)$. If $UâŠ®B âˆ§â–¡ C$, we're
     done. Otherwise, from ($â‹†$) Follows $U âˆˆ ğ’±$. From the definition of the world
     $c_U$ we have that $c_U \cancel{S}_v E$. So, $UâŠ® Dâ–· E$.
