stages:
  - org
  - pdf

org2tex:
  image: silex/emacs:26.3
  stage: org
  script:
    - cd report
    - emacs report.org --batch -f org-latex-export-to-latex --kill
    - cp -r img report.tex refs.bib .latexmkrc ../
  artifacts:
    paths:
    - report.tex
    - img
    - refs.bib
    - .latexmkrc
    - readme.org
    expire_in: 1 month

# the following job takes about 6 minutes to finish.
tex2pdf:
  stage: pdf
  # image: mirisbowring/texlive_ctan_full:2019
  # image: laurenss/texlive-full:2019
  # NOTE: need texlive 2020 to compile. Does not work with 2019 version.
  # image: danteev/texlive:latest
  image: nopreserveroot/texlive-full:2020.04.17
  only:
    - master
  script:
    - mkdir -p ~/.fonts/truetype/FreeMono
    - cp fonts/FreeMono.otf ~/.fonts/
    - latexmk -pdf report
  artifacts:
    paths:
    - report.pdf
    expire_in: 1 month

# To browse the latest generated .tex file, visit the following URL:
# https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/browse?job=org2tex
