image: silex/emacs:26.3

stages:
  - build

export:
  stage: build
  script:
      - cd report
      - emacs report.org --batch -f org-latex-export-to-latex --kill
      - cp report.tex ../
  artifacts:
    paths:
    - report.tex
