stages:
  - org

org2tex:
  image: silex/emacs:26.3
  stage: org
  script:
    - cd report
    - emacs report.org --batch -f org-latex-export-to-latex --kill
    - cp -r img report.tex refs.bib .latexmkrc ../
  artifacts:
    paths:
    - report.tex
    - img
    - refs.bib
    - .latexmkrc
    - readme.org
    expire_in: 1 month

# To browse the latest generated .tex file, visit the following URL:
# https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/browse?job=org2tex
