image: silex/emacs:26.3

stages:
  - build

export:
  stage: build
  script:
      - cd report
      - emacs report.org --batch -f org-latex-export-to-latex --kill
      - cp report.tex ../
      - cp -r img ../
  artifacts:
    paths:
    - report.tex
    - img/

# To browse the latest generated .tex file, visit the following URL:
# https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/browse?job=export
