stages:
  - org
  - pdf

org2tex:
  image: janmasrovira/emacs-org:27.0
  stage: org
  script:
    - cd report
    - emacs report.org -batch -l ~/init.el -f org-latex-export-to-latex
    - mv report.tex report1.tex
    - echo "% !TEX TS-program = xelatex" > header
    - cat header report1.tex > report.tex
    - cp -r img report.tex refs.bib .latexmkrc ../
  artifacts:
    paths:
    - report.tex
    - img
    - refs.bib
    - .latexmkrc
    - readme.org
    expire_in: 1 month

tex2pdf:
  stage: pdf
  # NOTE: need texlive 2020 to compile. Does not work with 2019 version.
  image: janmasrovira/texlive:2020-custom
  script:
    - mkdir -p ~/.fonts
    - cp fonts/*.otf ~/.fonts/
    - latexmk -pdf report
  artifacts:
    paths:
    - report.pdf
    expire_in: 1 year
