* Readme
  # You can find the latest build here: [[https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/file/report.pdf?job=tex2pdf]].

  Browse the pdf online using the following url:
#+begin_center
  [[https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/file/report.pdf?job=tex2pdf]]
#+end_center
  Or download it directly:
#+begin_center
  [[https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/raw/report.pdf?job=tex2pdf]]
#+end_center


  Note that this pdf's are generated using Gitlab's pipelines and I have set the
  expiration period to 1 month to avoid bloating the repository. This means that
  they will become unavailable eventually. It is pending to fix this.

** Compiling yourself
   The latest tex file can be found here:
   [[https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/browse?job=org2tex]].
   To download the TeX file and compile it automatically follow these commands or
   run the [[file:./scripts/get-pdf.sh][get-pdf.sh]] script:

   #+begin_example
   curl --location "https://gitlab.com/janmasrovira/masterlogic-thesis/-/jobs/artifacts/master/download?job=org2tex" --output artifacts.zip
   unzip artifacts.zip
   latexmk -pdf report
   #+end_example
   *Important: TeXLive 2020 is required.*

** Docker alternative
   If you don't have TeXLive 2020 you can use the [[file:./scripts/get-pdf-docker.sh][get-pdf-docker.sh]] script for a
   self-contained alternative.
   #+begin_example
   ./scripts/get-pdf-docker.sh workdir
   #+end_example
** Fonts
   Some extra fonts are required to compile, which can be found in
   [[file::./fonts]]. To install them on a unix-like system do:
   #+begin_example
   cp fonts/*.otf ~/.fonts/
   fc-cache -fv
   #+end_example
